apiVersion: v1
kind: Service
metadata:
  name: clusterip-service
  namespace: devops
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
