apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  namespace: devops
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
  - name: sidecar
    image: busybox
    command: ["sh", "-c", "while true; do echo hello; sleep 10;done"]
