name: Testing CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - uses: actions/checkout@v2
    - name: Testing CI
      run: echo "Hello World..."